N1=length(ODX0nm[ODX0nm[,2]==1,1])
Nall=sum(ODX0nm[,2])
Fmiss1ing=N1/Nall
Nspace=Nall/(1-Fmissing)
F7merspace=Nspace/1e9 
# the diversity of the phage library is less than the total 7-mer 
# because of some biases, 1e9 is just a rough quess
# The mimotope space is about 0.5% of the 7-mer space? 
# Yet compared to a random sample 80% of the space occupied by random seqs 
# is also densely occupied by mimotopes and the rest are sparsely populated by mimotopes (as seen in t-sne projection).
# Is there a fine structure in the 7-mer space where small domains alternate (covered/ not covered)?
# The distribution of clone sizes is due to the distribution of species generated by the assymetric amplification of the phage
# so the exact distribution itself is not important but the estimate of the size of the mimtope space is.